### PR TITLE
Fix log file name

### LINKED ISSUE #28: Wrong log file name
The log file is erroneously called `block_store.log`, it should be `transaction_store.log`.

https://github.com/koinos/koinos-transaction-store/blob/aa53ebd13d53cd4c5ab4bc62f649f86169dbc438/cmd/koinos-transaction-store/main.go#L83

### PR DESCRIPTION
**Pull request by sgerbino**
Resolves #28.

## Brief description
Change log file name to `transaction_store.log`.

## Checklist

- [ ] I have built this pull request locally
- [ ] I have ran the unit tests locally
- [ ] I have manually tested this pull request
- [ ] I have reviewed my pull request
- [ ] I have added any relevant tests

### CODE REVIEW

File: cmd/koinos-transaction-store/main.go [hunk 1]
```diff
@@ -80,7 +80,7 @@ func main() {
 	appID := fmt.Sprintf("%s.%s", appName, *instanceID)
 
 	// Initialize logger
-	logFilename := path.Join(util.GetAppDir(baseDir, appName), logDir, "block_store.log")
+	logFilename := path.Join(util.GetAppDir(baseDir, appName), logDir, "transaction_store.log")
```
Comment (mvandeberg) [inline cmd/koinos-transaction-store/main.go:83]: Should be `appName + ".log"`

**Review by mvandeberg — APPROVED** [review]
